### ISSUE TITLE
wyz dependency

### ISSUE THREAD

**Issue by kornelski** [ferrilab/bitvec#195]
This crate is quite popular (congrats!) but it depends on the [wyz](https://lib.rs/crates/wyz) crate, which is a rather odd collection of random bits of code. The wyz crate also has a super-outdated `typemap` in its "garbage" dependencies, which indirectly pulls in unmaintained [and insecure](https://rustsec.org/advisories/RUSTSEC-2020-0027) `traitobject` dependency. As a result a vulnerable dead crate appears in `Cargo.lock` of thousands of crates, and this upsets vulnerability scanners.

Can you drop the `wyz` dependency?

**Comment by myrrlyn** [comment]
Hi! I apologize for the long delay; since publishing v1 I've had a fairly stressful and busy life, especially this winter, and have not had the time or energy to check this repository in a timely manner. I'm trying to catch up now.

`wyz` is a utility bucket for parts of my work that are not actually part of `bitvec`'s own operation, but don't necessarily warrant a crate entirely of their own just yet. I rely firmly on its `fmt`, `bidi`, and `range` modules.

The garbage collector was an idle sketch from 2020 that has always been behind a feature gate and `bitvec` never actually used. Since I never did anything with it, it's been stripped and the version bumped.
