### ISSUE TITLE
Equivalent BitVec<u8> produce different Vec<u8>

### ISSUE THREAD

**Issue by matutter** [ferrilab/bitvec#205]
Creating a copy of a `BitVec<u8>`, manipulating it, converting to a `BitSlice<u8>`, then back to a `BitVec<u8>` produced an equivalent but different `BitVec`.

### Expected Behavior

`BitVec<T>` that are equivalent produce equivalent `Vec<t>` from `BitVec<T>::into_vec()`.

### Actual Behavior

Equivalent `BitVec<T>` do not produce the same `Vec<T>`.

### Reproduce

```rust#[test]
fn test_bitvec_1() {
  // Original value
  let t1 = "foo!".to_string();
  // Convert to bytes
  let b1 = t1.as_bytes();
  let h1 = hex::encode(b1);
  let bv1 = BitVec::<u8>::from_slice(b1);
  // Convert directly back to string
  let t2 = String::from_utf8_lossy(b1);
  let bv1_orig = bv1.clone();
  // Clone and mutate it.
  let mut bv2 = bv1.clone();
  bv2.insert(0, false);
  bv2.insert(0, false);
  bv2.insert(0, false);
  bv2.push(true);
  bv2.push(true);
  bv2.push(true);
  bv2.push(true);
  bv2.push(true);
  // Create a slice that should be equivalent to the original
  let bv3 = bv2[3..35].to_bitvec();
  let b3 = bv3.clone().into_vec();
  let t3 = String::from_utf8_lossy(&b3);
  println!("t1      : {}", t1);
  println!("t2      : {}", t2);
  println!("b1      : {:?}", b1);
  println!("h1      : {}", h1);
  println!("bv1 orig: {:?}", bv1_orig.to_string());
  println!("bv1     : {:?} ({})", bv1.to_string(), bv1.len());
  println!("bv2     : {:?} ({})", bv2.to_string(), bv2.len());
  println!("bv3     : {:?} ({})", bv3.to_string(), bv3.len());
  println!("b3      : {:?}", b3);
  println!("t3      : {}", t3);
  println!("bv1 == bv2: {}", bv1 == bv2);
  println!("bv1 == bv3: {}", bv1 == bv3);
}
```

### Result

Note the values of `t1`, `t2`, and `t3` should all be the same. `b3` is weird, how does a 32bit vector produce 5 ints?

```
t1      : foo!
t2      : foo!
b1      : [102, 111, 111, 33]
h1      : 666f6f21
bv1 orig: "[0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0]"
bv1     : "[0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0]" (32)
bv2     : "[0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1]" (40)
bv3     : "[0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0]" (32)
b3      : [48, 123, 123, 11, 1]
t3      : 0{{

bv1 == bv2: false
bv1 == bv3: true
```

**Comment by myrrlyn** [comment]
Hi! I apologize for the long delay; I have had a *very* stressful winter and have not had the time or energy to check this repository in a timely manner. I'm trying to catch up now.

You have encountered a side effect of the fact that `.into_vec()` performs a `memcpy` of the underlying storage, and does *not* do an `.into_iter().collect::<Self>().secret_cast::<Vec<T>>()`.

In order to force `BitVec` to behave the way you expect (which incurs a performance cost as it re-computes the entire storage region), you need to call [`.force_align()`](https://docs.rs/bitvec/1.0.1/bitvec/vec/struct.BitVec.html#method.force_align) first.

A `BitSlice` region (which `BitVec` owns) consists of three logical components:

- a pointer to the first `T` element of the buffer
- an index of the first live bit in the first element
- a count of all bits in the region

`BitSlice` can point to any bit in an element, and `BitVec` is just a `BitSlice` with a managed allocation. `BitVec` doesn't require that `bv[0]` points to the starting bit in an element, and `bs[non_start ..].to_bitvec()` happily preserves the non-starting index.

I don't have a good answer on how to deal with this. Re-encoding the storage buffer on clone makes clones take too long; *not* doing it makes raw views of the storage behave weirdly.

The main reason to access the underlying storage tends to be when using the crate to construct an I/O protocol buffer and then pass that memory off to a transport interface. `io::Write` and `io::Read` perform streaming re-encoding of the storage region, avoiding this problem; I *believe* that collecting/extending a `BitVec` from another `BitVec` also does it correctly, but my memory on how far I've pushed specialization is fuzzy.

----

Summary: this is "intended" behavior on my end, though clearly not "correct" on yours. Call `.force_align()` before `.into_vec()` and it will match your expectations.
