### ISSUE TITLE
[Question] Is is possible to use BitArray with const generics?

### ISSUE THREAD

**Issue by tmbull** [ferrilab/bitvec#217]
Hello, I am relatively new to Rust and just recently found out about const generics in Rust. I would like to know if it is possible to declare BitArrays using a const generic. Originally, I was trying to do this using const generics on a struct impl, but I have created the following contrived example function which results in the same compile error.

```
fn generic_test<const N: usize>() {
    let a = [0; N];
    let b = bitarr![0; N];
    type B = BitArr!(for N);
}
```

Error output:

```
error: could not compile `generic-bitarr` due to 2 previous errors; 3 warnings emitted
➜  generic-bitarr git:(master) ✗ cargo run
   Compiling generic-bitarr v0.1.0 (/Users/tristan.bull/dev/generic-bitarr)
error[E0401]: can't use generic parameters from outer function
  --> src/main.rs:29:24
   |
27 | fn generic_test<const N: usize>() {
   |                       - const parameter from outer function
28 |     let a = [0; N];
29 |     let b = bitarr![0; N];
   |                        ^ use of generic parameter from outer function

error[E0401]: can't use generic parameters from outer function
  --> src/main.rs:30:26
   |
27 | fn generic_test<const N: usize>() {
   |                       - const parameter from outer function
...
30 |     type B = BitArr!(for N);
   |           -              ^ use of generic parameter from outer function
   |           |
   |           help: try using a local generic parameter instead: `<N>`

```

I have read through the [const generic documentation](https://doc.rust-lang.org/reference/items/generics.html#const-generics), and my intuition tells me that the array works and the `bitarr`/`BitArr` macros don't for the same reason that the const generics can't be used in an inner function. However, I don't understand either the macros or const generics well enough to figure out if there is another way to declare the bit array. Thanks for the help!

**Comment by myrrlyn** [comment]
Hi! I apologize for the long delay; I have had a *very* stressful winter and have not had the time or energy to check this repository in a timely manner. I'm trying to catch up now.

Not in the way you want. Your examples fail to compile for two different insufficiencies in the const and generic systems.

1. `bitarr![0; N]` doesn't work because I cannot perform computation on type-level integers. In order to match C++'s `std::bitset<N>`, I need to be able to produce a type declaration that is `[T; bitvec::mem::elts::<T>(N)]`, and the compiler won't do that (yet). It's in the works; there's a feature gate for it, but I refuse to budge from the stable release series for major components like this.
2. Functions really, really, don't like propagating generic parameters to interior items. In order to make your typedecl work, you'd have to write `type B<const N: usize> = BitArr!(for N);` and then refer to it as `B<N>` everywhere you touch it inside your function. That's a limitation of the generic system in general, and has nothing to do with the generic item being an integer rather than a typename. You *can* do it right now, though (see [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=fn+example%3Cconst+N%3A+usize%3E%28%29+%7B%0A++++type+Arr%3Cconst+N%3A+usize%3E+%3D+%5Bu8%3B+N%5D%3B%0A++++let+zero+%3D+unsafe+%7B+std%3A%3Amem%3A%3Azeroed%3A%3A%3CArr%3CN%3E%3E%28%29+%7D%3B%0A%7D).

When the const generic system improves, I will cut a new major-version that replaces the `BitArray` type declaration with `BitArray<T: BitStore, O: BitOrder, const N: usize>` where `N` is the number of bits. I am waiting eagerly for this to happen, because it will simplify my maintenance and your usage. `BitArray<[u8; 20], Msb0>` is much less pleasant than `BitArray<u8, Msb0, 160>`, *plus*, under this system, you could use any length rather than being forced to always span the entire region. Can't represent, for example, a `<_, _, 4>` yet.

> To be clear: even when I *do* support a 4-bit array, the memory representation will always be a full integer. By-value regions cannot be subdivided like this.
