### ISSUE TITLE
`bitarr![const ...]` throws mismatched types

### ISSUE THREAD

**Issue by riklus** [ferrilab/bitvec#218]
This assignement throws an error:

```rust
use bitvec::prelude::*;
const INITIATE: BitArray<[u8; 2]> = bitarr![const u8, Lsb0; 0x06, 0x00];
```

```rust
error[E0308]: mismatched types
 --> src/main.rs:9:41
  |
9 |     const INITIATE: BitArray<[u8; 2]> = bitarr![const u8, Lsb0; 0x06, 0x00];
  |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an array with a fixed size of 2 elements, found one with 1 element
  |
  = note: expected struct `bitvec::array::BitArray<[u8; 2]>`
             found struct `bitvec::array::BitArray<[u8; 1]>`
  = note: this error originates in the macro `bitarr` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I don't understand why.
As far as I understand this `bitarr![const u8, Lsb0; 0x06, 0x00]`  means an array u8 of 2 elements.

### My system

`Darwin riklus-macbookpro.local 20.6.0 Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64 x86_64`
`cargo 1.67.1 (8ecd4f20a 2023-01-10)`
`rustc 1.67.1 (d5a82bbd2 2023-02-07)`
Target: `x86_64-apple-darwin`
Bitvec: `bitvec = "1.0.1"`

**Comment by myrrlyn** [comment]
Hi! I apologize for the long delay; I have had a *very* stressful winter and have not had the time or energy to check this repository in a timely manner. I'm trying to catch up now.

The values supplied to `bitarr!` *are not storage elements*. [They are bit values](https://docs.rs/bitvec/1.0.1/bitvec/macro.bitarr.html).

> Like `vec!`, it can accept a sequence of comma-separated bit values, or a semicolon-separated pair of a bit value and a repetition counter. Bit values may be any integer or name of a `const` integer, but should only be 0 or 1.

You can write `BitArray { data: [0x06, 0x00], ..BitArray::ZERO }` as a value literal. The `::new` function was not able to be made `const` at time of publishing (if I remember correctly) but I believe recent compilers can support it being `const`. I plan to make as many constructors `const fn` as possible in future releases, so that you would be able to write `BitArray::new([0x06, 0x00])` and have it work correctly.

Right now, you need `bitarr![const u8, Lsb0; 0, 1, 1, 0, 0, 0, 0, 0, 0]`.
